# This file generates the GitHub Actions matrix
# For more info, see: https://zmk.dev/docs/user-setup#builds

include:
  - board: nice_nano_v2
    shield: echo_left
    # Add the ZMK Studio RPC snippet
    snippets:
      - studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: echo_right
    # Add the ZMK Studio RPC snippet
    snippets:
      - studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: settings_reset