name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
      
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: echo_left
          - board: nice_nano_v2
            shield: echo_right

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize west workspace
        # This points west to your west.yml at the repo root
        run: west init -l .

      - name: Update west dependencies
        # This reads west.yml and downloads the 'zmk' project
        run: west update

      - name: Export Zephyr CMAKE package
        run: west zephyr-export

      - name: Build firmware
        # This command will now succeed because zmk/app will exist
        run: |
          west build -s zmk/app \
          -d "build/${{ matrix.shield }}_${{ matrix.board }}" \
          -b "${{ matrix.board }}" -- \
          -DSHIELD="${{ matrix.shield }}" \
          -DZMK_CONFIG="${{ github.workspace }}/echo"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}-${{ matrix.board }}
          path: build/${{ matrix.shield }}_${{ matrix.board }}/zephyr/zmk.uf2