name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
      
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: echo_left
          - board: nice_nano_v2
            shield: echo_right

    steps:
      - name: Checkout user config
        uses: actions/checkout@v4

      - name: Initialize west
        run: west init -l .

      - name: DEBUG - Show .west/config file
        # This will show us how west has configured the project.
        run: cat .west/config

      - name: Update west dependencies with verbose output
        # The -v flag will show detailed logs of what west is doing.
        run: west update -v

      - name: DEBUG - List files after west update
        run: ls -la

      - name: Export Zephyr CMAKE package
        run: west zephyr-export

      - name: Build firmware
        run: |
          west build -s zmk/app \
          -d "build/${{ matrix.shield }}_${{ matrix.board }}" \
          -b "${{ matrix.board }}" -- \
          -DSHIELD="${{ matrix.shield }}" \
          -DZMK_CONFIG="${{ github.workspace }}/config" \
          -Dsnippets="studio-rpc-usb-uart"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}-${{ matrix.board }}
          path: |
            build/${{ matrix.shield }}_${{ matrix.board }}/zephyr/zmk.uf2