name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
      
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: echo_left
          - board: nice_nano_v2
            shield: echo_right

    steps:
      - name: Prepare workspace directory
        run: mkdir zmk-workspace

      - name: Checkout user config into workspace
        uses: actions/checkout@v4
        with:
          path: zmk-workspace/config

      - name: Initialize west workspace
        working-directory: zmk-workspace
        run: west init -l config

      - name: Update west dependencies
        working-directory: zmk-workspace
        run: west update

      - name: Export Zephyr CMAKE package
        working-directory: zmk-workspace
        run: west zephyr-export

      - name: Build firmware
        working-directory: zmk-workspace
        run: |
          # The only change is adding the second '/config' to the ZMK_CONFIG path
          west build -s zmk/app \
          -d "build/${{ matrix.shield }}_${{ matrix.board }}" \
          -b "${{ matrix.board }}" -- \
          -DSHIELD="${{ matrix.shield }}" \
          -DZMK_CONFIG="${{ github.workspace }}/zmk-workspace/config/config" \
          -Dsnippets="studio-rpc-usb-uart"

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}-${{ matrix.board }}
          path: |
            zmk-workspace/build/${{ matrix.shield }}_${{ matrix.board }}/zephyr/zmk.uf2