name: 'Build ZMK Firmware'

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:3.5
      
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: nice_nano_v2
            shield: echo_left
          - board: nice_nano_v2
            shield: echo_right

    steps:
      - name: Create Workspace
        run: mkdir workspace

      - name: Checkout User Config into config/ subdirectory
        uses: actions/checkout@v4
        with:
          path: workspace/config

      - name: Initialize West from Workspace Root
        working-directory: workspace
        run: west init -l config

      - name: Update West Dependencies
        working-directory: workspace
        run: west update

      - name: Export Zephyr CMAKE package
        working-directory: workspace
        run: west zephyr-export

      - name: Build Firmware
        working-directory: workspace
        run: |
          west build -s zmk/app \
          -d "build/${{ matrix.shield }}_${{ matrix.board }}" \
          -b "${{ matrix.board }}" -- \
          -DSHIELD="${{ matrix.shield }}" \
          -DZMK_CONFIG="${{ github.workspace }}/workspace/config"

      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.shield }}-${{ matrix.board }}
          path: workspace/build/${{ matrix.shield }}_${{ matrix.board }}/zephyr/zmk.uf2